add easy redirects to fns
apollographql/orbiter pull request #3
Opened 2021-03-04 14:56 UTC by JakeDawkins

2021-03-05 08:01 UTC, abernix requested changes
I'd like us to agree on the value of/inclusion of/necessity of the `headers` before we land it, but this looks good to me!

2021-03-05 08:01 UTC, abernix commented on netlify.toml
> +  headers = {X-From = "Netlify"}
I know I had this in my example, but it's worth scrutinizing.  Do we actually get value from passing this header on the (outgoing, from Netlify's proxy) request that we're proxying?  Do we consider this "from" Netlify?  I mean it is Netlify doing the proxying at our request, but maybe we want to describe it as this root proxy?  Is there use in gathering that or leveraging that in our scripts?

Also worth noting that [`X-` prefixed headers are deprecated/discouraged](https://tools.ietf.org/html/rfc6648) (now).

If we think there's value in supplying a header on that at all on that request, would it be useful to apply something like this for our own scripts/logging:

```suggestion
  headers = {Apollo-Proxy-Rule = "from-root-config"}
```

If not, perhaps we should just scrap this header until we have a purpose for it.

```suggestion
```

2021-03-05 08:01 UTC, abernix commented on netlify.toml
> +  headers = {X-From = "Netlify"}
Same question as above.

2021-03-05 15:25 UTC, JakeDawkins commented on netlify.toml
> +  headers = {X-From = "Netlify"}
Yeah, that makes sense! Honestly, I wasn't 100% sure why that header was even there, or what its use was, so I have noo problem dropping it 😂

2021-03-05 15:26 UTC, JakeDawkins commented
Crap, ignore that WIP commit, I need to back that out

2021-03-08 15:27 UTC, abernix approved these changes

2021-03-08 17:28 UTC, EverlastingBugstopper approved these changes

2021-03-09 02:36 UTC, merged